#!/usr/bin/env python3
"""Generate each service's reference tables from the code that defines them.

    python3 scripts/gen_reference.py           # rewrite every service's reference
    python3 scripts/gen_reference.py --check    # fail if a committed file is stale

WHY THIS EXISTS

A doc audit found four false statements. Three were prose restating a mechanism
that a docstring already owned — and in every case the docstring HAD been updated
by the commit that broke the README. Two copies of one fact; the copy further
from the code rotted first.

`assert_docs.py` catches an entry that is MISSING. It cannot catch one whose
description has gone stale, because no expression over the source decides whether
a sentence is still true. Generating the tables removes that question: there is
one source, so there is nothing to disagree.

WHAT IT DELIBERATELY DOES NOT GENERATE

The prose. A README that only points at code is useless to the person a README is
for, and the hand-written explanations here are among the more valuable things in
the repository. Only the REFERENCE tables are generated — name, default, path,
method, and one sentence. Terse is correct for a reference; the paragraph that
says why the knob exists stays hand-written, upstream of the link.

Which is also the answer to the register objection: a field comment is written for
a maintainer and would read badly as documentation, so only its FIRST SENTENCE is
taken. A reference line wants an identifying phrase, not an essay.
"""

from __future__ import annotations

import ast
import re
import sys
from pathlib import Path

SERVICES = ("hookrelay", "hookjudge", "hookprobe")
BANNER = "<!-- generated by scripts/gen_reference.py — edit the code comments, not this file -->"
_SENTENCE = re.compile(r"^(.+?)(?:\.\s|\.$|$)", re.S)


def _first_sentence(text: str) -> str:
    """One line, collapsed. A reference row wants an identifying phrase."""
    # `|` ends a cell. A field comment reading "schema | tools | object" silently
    # produced three broken columns until this line existed.
    flat = " ".join(text.replace("`", "").replace("|", "\\|").split())
    match = _SENTENCE.match(flat)
    out = (match.group(1) if match else flat).strip()
    return (out[:180].rstrip() + "…") if len(out) > 180 else out


def _field_comments(source: str, class_name: str) -> dict[str, str]:
    """Field name -> the comment block written above it.

    Comments, not docstrings, because that is how this repo annotates dataclass
    fields — and a comment is invisible at runtime, so the text has to come from
    the file rather than from an import.
    """
    lines = source.splitlines()
    tree = ast.parse(source)
    node = next((n for n in ast.walk(tree) if isinstance(n, ast.ClassDef) and n.name == class_name), None)
    if node is None:
        return {}
    out: dict[str, str] = {}
    for stmt in node.body:
        if not isinstance(stmt, ast.AnnAssign) or not isinstance(stmt.target, ast.Name):
            continue
        collected: list[str] = []
        index = stmt.lineno - 2  # 0-based, line above the field
        while index >= 0 and lines[index].strip().startswith("#"):
            collected.append(lines[index].strip().lstrip("#").strip())
            index -= 1
        out[stmt.target.id] = " ".join(reversed(collected))
    return out


def _env_reads(node: ast.AST) -> list[tuple[str, str]]:
    """Every (ENV_NAME, default) read anywhere under `node`, in source order.

    Walks the whole subtree rather than looking at the first call, because
    `max(1, _int("HOOKPROBE_MAX_TURNS", 32))` hides the read one level down and a
    reference table that silently omits a knob is worse than none. Found by
    generating one and noticing 13 rows where the code reads 31.
    """
    found: list[tuple[str, str]] = []
    for call in (n for n in ast.walk(node) if isinstance(n, ast.Call)):
        if not call.args:
            continue
        first = call.args[0]
        if not (isinstance(first, ast.Constant) and isinstance(first.value, str) and first.value.isupper()):
            continue
        default = ast.unparse(call.args[1]) if len(call.args) > 1 else '""'
        found.append((first.value, default, call.lineno))
    return found


def _comment_above(lines: list[str], lineno: int) -> str:
    """The `#` block directly above a 1-based line. Same rule as a field comment,
    so a knob read outside the dataclass is described the same way."""
    collected: list[str] = []
    index = lineno - 2
    while index >= 0 and lines[index].strip().startswith("#"):
        collected.append(lines[index].strip().lstrip("#").strip())
        index -= 1
    return " ".join(reversed(collected))


def _env_bindings(source: str) -> list[tuple[str, str, str]]:
    """(field, ENV_NAME, default) for every variable `load()` reads.

    Pairing exists only to attach the comment written beside the field, so a read
    that cannot be paired is still listed — with no description rather than not at
    all. Locals are resolved because `load()` reads several into a variable first
    and then passes the variable.
    """
    tree = ast.parse(source)
    load = next((n for n in ast.walk(tree) if isinstance(n, ast.FunctionDef) and n.name == "load"), None)
    if load is None:
        return []

    # local name -> the env var it was read from
    locals_from_env: dict[str, str] = {}
    for stmt in load.body:
        if isinstance(stmt, ast.Assign) and len(stmt.targets) == 1 and isinstance(stmt.targets[0], ast.Name):
            reads = _env_reads(stmt.value)
            if reads:
                locals_from_env[stmt.targets[0].id] = reads[0][0]

    field_of: dict[str, str] = {}
    for call in (n for n in ast.walk(load) if isinstance(n, ast.Call)):
        for kw in call.keywords:
            if kw.arg is None:
                continue
            for env, _, _ in _env_reads(kw.value):
                field_of.setdefault(env, kw.arg)
            for name in (n.id for n in ast.walk(kw.value) if isinstance(n, ast.Name)):
                if name in locals_from_env:
                    field_of.setdefault(locals_from_env[name], kw.arg)

    seen: dict[str, str] = {}
    for env, default, _ in _env_reads(load):
        seen.setdefault(env, default)
    return [(field_of.get(env, ""), env, default) for env, default in seen.items()]


def _routes(service: str) -> list[tuple[str, str, str]]:
    """(METHOD, path, one sentence) for every mounted route in the service."""
    rows: list[tuple[str, str, str]] = []
    for path in sorted(Path(service, service).glob("*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            if not isinstance(node, ast.AsyncFunctionDef | ast.FunctionDef):
                continue
            for deco in node.decorator_list:
                if not (isinstance(deco, ast.Call) and isinstance(deco.func, ast.Attribute)):
                    continue
                verb = deco.func.attr
                if verb not in ("get", "post", "put", "delete") or not deco.args:
                    continue
                target = deco.args[0]
                if not (isinstance(target, ast.Constant) and isinstance(target.value, str)):
                    continue
                doc = ast.get_docstring(node) or ""
                rows.append((verb.upper(), target.value, _first_sentence(doc) if doc else "—"))
    rows.sort(key=lambda r: (r[1], r[0]))
    return rows


UNDESCRIBED: dict[str, list[str]] = {}


def render(service: str) -> str:
    settings_src = Path(service, service, "settings.py").read_text(encoding="utf-8")
    comments = _field_comments(settings_src, "Settings")
    bindings = _env_bindings(settings_src)
    # Knobs read outside Settings — HOST and PORT live in __main__ because the
    # server reads them, not the service. Listed anyway: an operator setting a
    # variable does not care which module happens to read it, and a reference
    # that omits one is the failure this file exists to prevent.
    known = {env for _, env, _ in bindings}
    outside: dict[str, str] = {}
    for module in sorted(Path(service, service).glob("*.py")):
        if module.name == "settings.py":
            continue
        text = module.read_text(encoding="utf-8")
        lines = text.splitlines()
        for env, default, lineno in _env_reads(ast.parse(text)):
            if env.startswith(service.upper()) and env not in known:
                known.add(env)
                outside[env] = _comment_above(lines, lineno)
                bindings.append((env, env, default))
    comments = {**comments, **outside}
    routes = _routes(service)

    out = [
        BANNER,
        "",
        f"# {service} — reference",
        "",
        "Generated from the code: environment names and defaults from `settings.py`,",
        "routes and their first sentence from the handlers. Correct it by editing the",
        "comment beside the field or the handler's docstring — an edit here is lost on",
        "the next run, and `scripts/gen_reference.py --check` will say so.",
        "",
        f"## Environment ({len(bindings)})",
        "",
        "| variable | default | what it is |",
        "| --- | --- | --- |",
    ]
    for field, env, default in bindings:
        # `'hookjudge.db'` renders the Python literal's quotes; a reference table
        # wants the value. Expressions like `256 * 1024` are left as written —
        # evaluating them would hide the shape somebody chose to express.
        literal = default.strip()
        if literal in ('""', "''"):
            shown = "*(empty)*"
        else:
            shown = f"`{literal[1:-1] or ''}`" if literal[:1] in "\"'" and literal[-1:] == literal[:1] else f"`{literal}`"
        described = _first_sentence(comments.get(field, ""))
        if not described:
            UNDESCRIBED.setdefault(service, []).append(env)
        out.append(f"| `{env}` | {shown} | {described or '—'} |")
    out += ["", f"## Routes ({len(routes)})", "", "| method | path | what it does |", "| --- | --- | --- |"]
    for verb, path, doc in routes:
        out.append(f"| {verb} | `{path}` | {doc} |")
    out.append("")
    return "\n".join(out)


def main(argv: list[str]) -> int:
    check = "--check" in argv
    stale: list[str] = []
    for service in SERVICES:
        target = Path(service, "docs", "reference.md")
        wanted = render(service)
        if check:
            current = target.read_text(encoding="utf-8") if target.is_file() else ""
            if current != wanted:
                stale.append(str(target))
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(wanted, encoding="utf-8")
        print(f"  wrote {target}")

    if check and UNDESCRIBED:
        print("knobs with no description:", file=sys.stderr)
        for service, names in UNDESCRIBED.items():
            for name in names:
                print(f"  {service}: {name}", file=sys.stderr)
        print(
            "\nWrite a `#` comment above the field in settings.py. The reference takes its\n"
            "first sentence, so one line is enough.\n\n"
            "This replaced an older rule that every knob must ALSO be named in a README. That\n"
            "rule made a second copy of the fact, which is what put four false statements in\n"
            "the docs to begin with. A comment beside the field cannot drift from the field.",
            file=sys.stderr,
        )
        return 1

    if stale:
        print("reference docs are stale:", file=sys.stderr)
        for name in stale:
            print(f"  {name}", file=sys.stderr)
        print(
            "\nRun `python3 scripts/gen_reference.py` and commit the result. These files are\n"
            "generated so that a description cannot drift from the code that defines it; a\n"
            "stale one means the generator ran and the output was not committed.",
            file=sys.stderr,
        )
        return 1
    if check:
        print(f"reference: {len(SERVICES)} generated docs match the code they are generated from")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
